const CONFIG = {
  SERVER:     'http://localhost:5001',
  CHUNK_MS:   500,
  SEND_EVERY: 500,
  EMOTION_EVERY_MS: 3000,

  QUESTIONS: [
    "{w}.",
    "...{w}?",
    "{w}, maybe.",
    "something like {w}...",
    "not quite {w}. or is it.",
    "this feels like {w}.",
    "there is {w} in this.",
    "almost {w}.",
    "...is this {w}?",
    "{w}. no. something else.",
    "not {w}. and yet.",
    "closer to {w} than anything.",
    "if {w} had a sound...",
    "the shape of {w}.",
    "what {w} sounds like.",
    "somewhere between {w} and silence.",
    "i think i recognise {w}.",
    "i keep returning to {w}.",
    "it keeps reading as {w}.",
    "the model says {w}.",
  ],

  WARP: {
    scale:    4.0,
    strength: 0.35,
    sigma:    0.22,
    speed:    0.15,
  },

  EMOTION_HUES: {
    "melancholy":   240, "grief":        250, "despair":      260,
    "dread":        270, "numbness":     220, "coldness":     200,
    "void":         230, "hollow":       215, "frozen":       195,
    "collapse":     245, "dissolve":     235, "fractured":    255,
    "joy":           45, "euphoria":      55, "warmth":        30,
    "wonder":        40, "awe":           50, "bloom":         80,
    "surge":         20, "burning":       15, "fire":          10,
    "tension":        0, "rage":           5, "sharp":        355,
    "turbulence":   350, "restlessness": 340, "pulse":        345,
    "peace":        140, "serenity":     150, "tenderness":   130,
    "earth":        100, "fluid":        160, "drift":        155,
    "smooth":       145, "vast":         280, "infinite":     290,
    "ancient":      300, "boundless":    285, "longing":      210,
    "intimate":     170, "fragile":      180, "raw":           25,
    "coarse":        35, "rough":         20, "heavy":        230,
    "light":         60, "dense":        240, "brittle":      200,
    "delicate":     170, "water":        195, "trembling":    260,
    "stillness":    185, "soft":         120,
  },
};
